volumes:
  opensearch: {}
  data: {}

networks:
  default: {}

services:
  nginx:
    image: docker.io/library/nginx:1.31-alpine
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - data:/data
    networks:
      default:
        aliases:
          - auth.localtest.me
          - auth-proxy.localtest.me
          - cdn.localtest.me
          - default.localtest.me
          - tenant-a.localtest.me
          - tenant-b.localtest.me

  opencast:
    image: quay.io/opencast/allinone:20
    hostname: opencast
    healthcheck:
      disable: true
    environment:
      ORG_OPENCASTPROJECT_SERVER_URL: http://opencast:8080
      ORG_OPENCASTPROJECT_DOWNLOAD_URL: http://cdn.localtest.me
      ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER: admin
      ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS: opencast
      ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER: opencast_system_account
      ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS: CHANGE_ME
      ELASTICSEARCH_SERVER_HOST: opensearch
      OPENCAST_DISPATCH_INTERVAL: '1'
      KARAF_DEBUG: '1'
      JAVA_DEBUG_OPTS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
    ports:
      - "5005:5005"
    volumes:
      - ./services/opencast/etc/security:/etc/opencast/security:ro
      - ./services/opencast/etc/org.opencastproject.organization-mh_default_org.cfg:/etc/opencast/org.opencastproject.organization-mh_default_org.cfg:ro
      - ./services/opencast/etc/org.opencastproject.organization-tenant-a.cfg:/etc/opencast/org.opencastproject.organization-tenant-a.cfg:ro
      - ./services/opencast/etc/org.opencastproject.organization-tenant-b.cfg:/etc/opencast/org.opencastproject.organization-tenant-b.cfg:ro
      - ./services/opencast/etc/org.opencastproject.userdirectory.UserIdRoleProvider.cfg:/etc/opencast/org.opencastproject.userdirectory.UserIdRoleProvider.cfg:ro
      - data:/data

  opensearch:
    image: opencast/opensearch:1
    build:
      dockerfile_inline: |
        FROM docker.io/opensearchproject/opensearch:1
        RUN bin/opensearch-plugin install analysis-icu
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: 'true'
      OPENSEARCH_JAVA_OPTS: -Xms128m -Xmx512m
      DISABLE_INSTALL_DEMO_CONFIG: 'true'
      DISABLE_SECURITY_PLUGIN: 'true'
    volumes:
      - opensearch:/usr/share/opensearch/data

  dex:
    image: ghcr.io/dexidp/dex:v2.45.1-distroless
    restart: on-failure
    command: dex serve --web-http-addr 0.0.0.0:5556 --telemetry-addr 0.0.0.0:5558 /etc/dex/config.yaml
    volumes:
      - ./services/dex/etc/config.yaml:/etc/dex/config.yaml:ro

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.15.4-alpine
    restart: on-failure
    environment:
      # General Provider Options
      OAUTH2_PROXY_APPROVAL_PROMPT: "auto"
      OAUTH2_PROXY_CLIENT_ID: "auth-proxy.localtest.me"
      OAUTH2_PROXY_CLIENT_SECRET: "secret"
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: "S256"
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "false"
      OAUTH2_PROXY_INSECURE_OIDC_SKIP_ISSUER_VERIFICATION: "false"
      OAUTH2_PROXY_INSECURE_OIDC_SKIP_NONCE: "false"
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: "Example SSO"
      OAUTH2_PROXY_PROVIDER: "oidc"
      OAUTH2_PROXY_SCOPE: "openid email profile groups federated:id"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "http://auth.localtest.me"
      # Cookie Options
      OAUTH2_PROXY_COOKIE_DOMAINS: ".localtest.me"
      OAUTH2_PROXY_COOKIE_EXPIRE: "168h0m0s" # = 7d
      OAUTH2_PROXY_COOKIE_REFRESH: "24h0m0s" # = 1d
      OAUTH2_PROXY_COOKIE_NAME: "auth-proxy"
      OAUTH2_PROXY_COOKIE_SECRET: "RHRhdlRhRlg0a1dCdVprT01lbDVyZmRrYVhxSTM1L2M="
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      # Header Options
      OAUTH2_PROXY_PASS_BASIC_AUTH: "false"
      OAUTH2_PROXY_PASS_USER_HEADERS: "false"
      OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
      # Logging Options
      OAUTH2_PROXY_AUTH_LOGGING: "false"
      OAUTH2_PROXY_REQUEST_LOGGING: "false"
      OAUTH2_PROXY_SILENCE_PING_LOGGING: "true"
      # Page Template Options
      # -
      # Probe Options
      # -
      # Proxy Options
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_REDIRECT_URL: "http://auth-proxy.localtest.me/oauth2/callback"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_WHITELIST_DOMAINS: ".localtest.me"
      # Server Options
      OAUTH2_PROXY_HTTP_ADDRESS: ":4180"
      # Session Options
      # Upstream Options
      # -
