volumes:
  moodle-db: {}

services:
  moodle-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: moodle
      POSTGRES_DB: moodle
    volumes:
      - moodle-db:/var/lib/postgresql/data

  moodle:
    build:
      context: ./services/moodle
      args:
        MOODLE_PHP_APACHE: "8.4"
        MOODLE_VERSION: "v5.0.1"
        MOODLE_LOCAL_CHUNKUPLOAD: "upgrade-500"
        MOODLE_REPOSITORY_OPENCAST: "upgrade-500"
        MOODLE_FILTER_OPENCAST: "upgrade-500"
        MOODLE_TOOL_OPENCAST: "upgrade-500"
        MOODLE_MOD_OPENCAST: "upgrade-500"
        MOODLE_BLOCK_OPENCAST: "upgrade-500"
    restart: on-failure
    environment:
      WWWROOT: http://moodle.localtest.me
      ADMINPASS: moodle
      OC_API_PASSWORD: moodle
    volumes:
      - ./services/moodle/rootfs/var/www/html/admin/cli/init_plugin_configs.php:/var/www/html/admin/cli/init_plugin_configs.php:ro
