access_log off;

proxy_set_header Host               $http_host;
proxy_set_header X-Real-IP          $remote_addr;
proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto  $scheme;
proxy_set_header X-Scheme           $scheme;

proxy_request_buffering off;

resolver 127.0.0.11 valid=10s;

# Default server
server {
  listen      80 default_server;
  server_name _;

  location / {
    return 404;
  }
}

# serve static files
server {
  listen      80;
  server_name cdn.localtest.me;

  add_header Access-Control-Allow-Origin       *                                               always;
  add_header Access-Control-Allow-Credentials  true                                            always;
  add_header Access-Control-Allow-Methods      "OPTIONS, HEAD, GET"                            always;
  add_header Access-Control-Allow-Headers      "Accept-Encoding,Authorization,DNT,If-Match,If-Modified-Since,If-None-Match,If-Unmodified-Since,Origin,Referer,User-Agent,X-Request-ID,X-Requested-With" always;
  add_header Access-Control-Max-Age            86400                                           always;

  # Always respond with 200 to OPTIONS requests as browsers do not accept
  # non-200 responses to CORS preflight requests.
  if ($request_method = OPTIONS) {
      return 200;
  }

  root /data/opencast/downloads;
}

# reverse proxy to dex
server {
  listen      80;
  server_name auth.localtest.me;

  location / {
    set $docker_host dex:5556;
    proxy_pass http://$docker_host;
  }
}

# reverse proxy to oauth2-proxy
server {
  listen      80;
  server_name auth-proxy.localtest.me;

  location / {
    set $docker_host oauth2-proxy:4180;
    proxy_pass http://$docker_host;
  }
}

# reverse proxy to Opencast
server {
  listen      80;
  server_name ~^(default|tenant-a|tenant-b)\.localtest\.me$;

  location /oauth2/ {
    proxy_set_header Host                    $http_host;
    proxy_set_header X-Real-IP               $remote_addr;
    proxy_set_header X-Forwarded-For         $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto       $scheme;
    proxy_set_header X-Scheme                $scheme;
    proxy_set_header X-Auth-Request-Redirect $request_uri;

    set $docker_host1 oauth2-proxy:4180;
    proxy_pass http://$docker_host1;
  }

  location = /oauth2/auth {
    proxy_set_header Host               $http_host;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Scheme           $scheme;
    proxy_set_header Content-Length     "";

    set $docker_host2 oauth2-proxy:4180;
    proxy_pass http://$docker_host2;
  }

  location / {
    auth_request /oauth2/auth;
    auth_request_set $auth        $upstream_http_authorization;
    auth_request_set $auth_cookie $upstream_http_set_cookie;
    error_page 401 = /oauth2/sign_in?rd=$scheme://$host$request_uri;

    add_header Set-Cookie $auth_cookie;

    client_max_body_size 10g;

    proxy_read_timeout 20m;

    proxy_set_header Host              $http_host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Scheme          $scheme;
    proxy_set_header Authorization     $auth;

    set $docker_host3 opencast:8080;
    proxy_pass http://$docker_host3;
  }
}
